REDSHOP-3723 Can't save Zipcode
redCOMPONENT-COM/redSHOP pull request #4172
Opened 2018-02-06 12:22 UTC by NguyenBao10

2018-02-26 02:43 UTC, ThongTran-Dev requested changes

2018-02-27 04:07 UTC, ThongTran-Dev requested changes

2018-03-06 08:33 UTC, ThongTran-Dev requested changes

2018-06-12 10:27 UTC, khoaredweb requested changes
@NguyenBao10 please check my comment

2018-07-11 09:26 UTC, soulevilx requested changes

2018-07-31 08:13 UTC, soulevilx requested changes

2018-08-10 08:07 UTC, soulevilx requested changes

2018-08-21 05:03 UTC, soulevilx approved these changes

2018-09-04 03:15 UTC, merged