REDSHOP-4890 "Edit" button working incorrect in Catalogue mangement
redCOMPONENT-COM/redSHOP pull request #4230
Opened 2018-03-02 08:58 UTC by NguyenBao10

2018-06-06 10:47 UTC, soulevilx requested changes

2018-06-12 10:54 UTC, khoaredweb requested changes
@NguyenBao10 please check my comment

2018-07-12 06:23 UTC, soulevilx requested changes
Please check my comments

2018-07-18 10:25 UTC, soulevilx approved these changes

2018-07-18 10:26 UTC, merged