REDSHOP-5119 Fix Shipping rate - User can't delete country
redCOMPONENT-COM/redSHOP pull request #4362
Opened 2018-06-25 09:27 UTC by hungnguyenckc

2018-06-29 04:28 UTC, lunguyenhat approved these changes

2018-07-16 07:30 UTC, soulevilx requested changes

2018-07-16 08:08 UTC, soulevilx requested changes
Please check my comments

2018-08-10 03:31 UTC, soulevilx requested changes

2018-08-10 06:00 UTC, soulevilx requested changes

2018-08-20 10:14 UTC, soulevilx approved these changes

2018-08-20 10:15 UTC, merged