REDSHOP-5129 Fix Product detail - Not show supplier in Product detail
redCOMPONENT-COM/redSHOP pull request #4366
Opened 2018-06-27 03:29 UTC by hungnguyenckc

2018-06-29 04:35 UTC, lunguyenhat approved these changes

2018-07-12 08:52 UTC, soulevilx requested changes
Please merge with develop to get latest automation code fixing.
Your PR is not passed Jenkins .

cc @hungnguyenckc

2018-07-16 07:44 UTC, soulevilx approved these changes

2018-07-16 07:46 UTC, soulevilx requested changes
Please check my comments

2018-08-10 03:35 UTC, soulevilx requested changes

2018-08-20 10:17 UTC, merged