REDSHOP-5050 Checkout with change quantity product
redCOMPONENT-COM/redSHOP pull request #4410
Opened 2018-07-23 10:41 UTC by VanTrieuThanh96

2018-07-24 10:19 UTC, nhungredweb reviewed
Please ready my comment . thanks

2018-07-25 07:14 UTC, nhungredweb reviewed
i make 2 comment , the rest is look good for me . thanks

2018-07-26 10:32 UTC, nhungredweb approved these changes
the PR is look good for me . thank for your attention so much .

2018-07-26 12:53 UTC, puneet0191 requested changes

2018-08-03 03:36 UTC, nhungredweb approved these changes

2018-08-03 10:56 UTC, merged