REDSHOP-5204 Fix calendar form field broken after upgrading redshop
redCOMPONENT-COM/redSHOP pull request #4473
Opened 2018-09-25 04:59 UTC by ducredweb

2018-10-04 00:35 UTC, jatitoam submitted a review, later dismissed

2018-12-21 07:59 UTC, jatitoam submitted a review, later dismissed

2018-12-25 08:28 UTC, khoaredweb requested changes
Please check my comments. Btw, I think this function "fixCurrentConfig" should be put into "/component/admin/updates/2.1.1.php" instead

2019-01-09 03:43 UTC, lunguyenhat approved these changes

2019-01-09 03:50 UTC, merged