REDSHOP-2543 Tests for EWAY Payment Plugin
redCOMPONENT-COM/redSHOP pull request #4817
Opened 2019-06-21 07:37 UTC by NguyenTrang091296

2019-07-16 03:50 UTC, nhungredweb requested changes
@NguyenTrang091296  all is look good for me. just help me update a bit for since . we ready for 2.1.3 . 
https://github.com/redCOMPONENT-COM/redSHOP/releases

2019-08-07 06:34 UTC, nhungredweb requested changes

2019-08-07 10:19 UTC, nhungredweb submitted a review, later dismissed

2019-08-22 06:51 UTC, PhamHanh96 requested changes

2019-08-23 08:29 UTC, PhamHanh96 submitted a review, later dismissed

2019-08-26 06:14 UTC, PhamHanh96 requested changes

2019-08-26 10:37 UTC, PhamHanh96 submitted a review, later dismissed

2019-09-13 06:34 UTC, PhamHanh96 requested changes

2019-09-13 07:20 UTC, PhamHanh96 approved these changes

2019-09-13 08:02 UTC, merged