REDSHOP-2788 VAT is changed depending on the user
redCOMPONENT-COM/redSHOP pull request #4878
Opened 2019-08-22 10:18 UTC by hoanghairedweb

2019-08-26 03:49 UTC, NguyenTrang091296 requested changes

2019-08-29 07:04 UTC, NguyenTrang091296 requested changes

2019-09-04 02:42 UTC, NguyenTrang091296 requested changes

2019-09-04 10:30 UTC, PhamHanh96 requested changes
@hoanghairedweb I left some comments, pls recheck. Ring a bell if you need any help. Thanks!

2019-09-10 03:50 UTC, PhamHanh96 requested changes
@hoanghairedweb It's look good for me, but we need to update a bit for better. Pls help update. Thanks!

2019-09-10 06:22 UTC, PhamHanh96 submitted a review, later dismissed
Everything looks good for me, thank @hoanghairedweb so much!

2019-09-11 02:32 UTC, NguyenTrang091296 requested changes

2019-09-12 02:04 UTC, NguyenTrang091296 approved these changes

2019-09-12 02:04 UTC, merged