REDSHOP-5637 Hide Shipping method when checkout has 1 shipping item
redCOMPONENT-COM/redSHOP pull request #5028
Opened 2019-12-31 10:04 UTC by hungnguyenckc

2019-12-31 10:10 UTC, ducredweb submitted a review, later dismissed

2019-12-31 10:14 UTC, ducredweb submitted a review, later dismissed

2020-01-02 10:28 UTC, anhredweb requested changes
@hungnguyenckc , @NguyenTrang091296 please help to check my comment.
Thanks.

2020-01-03 02:59 UTC, anhredweb submitted a review, later dismissed

2020-01-06 02:17 UTC, anhredweb approved these changes

2020-01-06 02:17 UTC, merged