REDSHOP-5660 Update file README.md. Support run automation on local
redCOMPONENT-COM/redSHOP pull request #5041
Opened 2020-01-06 04:06 UTC by NguyenTrang091296

2020-01-06 06:58 UTC, anhredweb submitted a review, later dismissed

2020-01-06 08:24 UTC, ducredweb requested changes
@NguyenTrang091296    I found wrong markdown syntax on your README.md
https://github.com/NguyenTrang091296/redSHOP/blob/REDSHOP-5660/tests/README.md

(the h3 with ### not parsed correcty)

2020-01-06 09:44 UTC, anhredweb submitted a review, later dismissed

2020-01-08 03:09 UTC, anhredweb submitted a review, later dismissed

2020-01-09 03:21 UTC, merged