REDSHOP-5945 [Reractor][Component][Site] Move to use Twig for view Account
redCOMPONENT-COM/redSHOP pull request #5275
Opened 2020-03-23 05:18 UTC by hungnguyenckc

2020-03-23 05:34 UTC, hungnguyenckc commented
@anhredweb in the PR i just reformat code and move page heading use twig.

The current layouts it was refactored in PR following:

account/tmpl/cards: i think it no need move to use twig.
account/tmpl/default: refactor in PR #5237 
account/tmpl/mytags: refactor in PR #5271 
account/tmpl/mywishlist: refactor in PR #5142 and #5203

2020-03-24 03:36 UTC, anhredweb submitted a review, later dismissed

2020-03-25 04:09 UTC, anhredweb commented on component/site/views/account/view.html.php
> +	private function layoutMytags()
@hungnguyenckc : missing DocBlock for every new functions created by you

2020-03-25 04:11 UTC, anhredweb commented on component/site/views/account/view.html.php
> +		$layout = $this->input->getCmd('layout', 'default');
@hungnguyenckc : As my opinion `->getString` is better than `getCmd`, because it's has more strictly filter for data you get

2020-03-25 04:15 UTC, anhredweb commented on component/site/views/account/view.html.php
> +		if (($this->user->id == 0 && $layout != 'mywishlist') || ($this->user->id == 0 && $layout == 'mywishlist' && !isset($mail))) {
@hungnguyenckc : just one advice for more security, using `===` that ensure type of input the same, some hack tips can be use base64 encode and fetch bad purpose, `==` is implicit convert then compare data with no care type of value.

2020-03-25 04:16 UTC, anhredweb requested changes
@hungnguyenckc 
1. please help to add docblock to your new functions
2. some suggest for best practice.

Thanks,
H.A

2020-03-25 06:40 UTC, anhredweb approved these changes

2020-03-25 07:09 UTC, merged