REDSHOP-5949: Admin > Order detail view > Update discount error
redCOMPONENT-COM/redSHOP pull request #5361
Opened 2020-06-03 08:11 UTC by hoang-tran-redweb

add style error when display message error

2020-06-04 04:59 UTC, anhredweb commented on component/admin/controllers/order_detail.php
>              $msg = JText::_('COM_REDSHOP_DISCOUNT_UPDATED');
@hoang-tran-redweb : please also set $type = 'success' for of coming `else` condition

2020-06-04 05:00 UTC, anhredweb requested changes
@hoang-tran-redweb please careful for variable when using, missing $type definition for success case may lead to warning or notice.

2020-06-04 05:00 UTC, anhredweb commented on component/admin/controllers/order_detail.php
>              $msg = JText::_('COM_REDSHOP_SPECIAL_DISCOUNT_APPLIED');
@hoang-tran-redweb same here.

2020-06-05 07:10 UTC, anhredweb submitted a review, later dismissed

2020-06-08 09:05 UTC, VanTrieuThanh commented
@hoang-tran-redweb help me check with Scrutinizer

2020-06-17 10:43 UTC, anhredweb approved these changes

2020-06-17 10:45 UTC, merged