change css Filter bar of Order Detail & another detail page in Admin
redCOMPONENT-COM/redSHOP pull request #5369
Opened 2020-06-09 04:32 UTC by Hoangvan14999

2020-06-09 08:30 UTC, ducredweb commented
@hoangvan149dhv  please also make change to `redshop.admin.css`

2020-06-09 10:16 UTC, ducredweb submitted a review, later dismissed

2020-07-03 04:26 UTC, anhredweb submitted a review, later dismissed

2020-07-03 04:31 UTC, anhredweb commented
@hoangvan149dhv please name PR REDSHOP-XXXX with correct number with JIRA issue.

Thanks.

2020-07-06 08:18 UTC, anhredweb submitted a review, later dismissed

2020-07-06 09:38 UTC, anhredweb commented on apt-get
> +1
@hoangvan149dhv What is this file? please remove it.

2020-07-06 09:40 UTC, anhredweb commented on media/com_redshop/css/redshop.admin.css
> +    margin-bottom: 4px;
@hoangvan149dhv : please use combined way code:
`margin: 4px 10px 4px 0px;` means: top right bottom left. Please ref here: https://www.w3schools.com/css/css_margin.asp

2020-07-06 09:42 UTC, anhredweb commented on media/com_redshop/css/redshop.admin.min.css
> -    margin: 10px 4px 4px;
@hoangvan149dhv This is not MIN CSS file. Please make sure this file is minified before using.

2020-07-06 09:43 UTC, anhredweb requested changes
@hoangvan149dhv Please update code for change request. Please do not hesitate for asking your colleges if you do not know how to fix.

2020-08-10 04:29 UTC, anhredweb commented
@hoangvan149dhv please fix conflict and do minify CSS. If you are not clear please ask backender about those needful changes
Thanks.

2020-08-12 07:49 UTC, closed without merging