REDSHOP-6064 Add Price - The field does not accept decimal values
redCOMPONENT-COM/redSHOP pull request #5421
Opened 2020-07-09 11:19 UTC by NguyenBao10

2020-07-10 10:07 UTC, hungnguyenckc submitted a review, later dismissed

2020-07-13 05:18 UTC, anhredweb requested changes
@NguyenBao10 : please check my comment.

2020-07-13 06:20 UTC, anhredweb commented on component/admin/views/prices_detail/tmpl/default.php
> -                               oninput="validity.valid || (value='');"
@NguyenBao10 if function validity.valid is wrong, please fix, remove valid checking is not best practice.

Thanks.

2020-07-13 06:23 UTC, anhredweb submitted a review, later dismissed

2020-07-14 07:39 UTC, anhredweb approved these changes

2020-07-14 07:39 UTC, merged