REDSHOP-4110: REFACTOR: Wrapper
redCOMPONENT-COM/redSHOP pull request #5436
Opened 2020-07-16 10:04 UTC by hoang-tran-redweb

refactor wrapper

2020-07-17 02:57 UTC, hungnguyenckc requested changes

2020-07-17 02:57 UTC, hungnguyenckc commented on component/admin/controllers/wrapper.php
> +	public function save($key = null, $urlVar = null)
@hoang-tran-redweb i see you no change any in this function so please remove it and use parent class

2020-07-17 02:57 UTC, hungnguyenckc commented on component/admin/controllers/wrappers.php
> +	public function FVpublish()
@hoang-tran-redweb i think this function is redundancy when refactor it will use function published of parent class

2020-07-17 02:57 UTC, hungnguyenckc commented on component/admin/controllers/wrappers.php
> +	public function FVunpublish()
same comment above

2020-07-17 02:57 UTC, hungnguyenckc commented on component/admin/sql/install/mysql/install.sql
>    `createdate` INT(11) NOT NULL,
please add column 
checked_out
checked_out_time
created_by
created_date
modified_by
modified_date

2020-07-17 02:57 UTC, hungnguyenckc commented on component/admin/sql/updates/mysql/3.0.3.sql
> +CALL redSHOP_Index_Remove('#__redshop_wrapper', 'idx_wrapper_use_to_all');
please add column 
checked_out
checked_out_time
created_by
created_date
modified_by
modified_date

2020-07-17 02:57 UTC, hungnguyenckc commented on component/admin/views/wrapper/view.html.php
> +	protected function prepareField($field)
if no any change please remove function

2020-07-20 02:12 UTC, anhredweb commented
@hungnguyenckc please re-check review code while @hoang-tran-redweb updated his code.
Thanks.

2020-07-20 02:38 UTC, hungnguyenckc requested changes

2020-07-20 02:38 UTC, hungnguyenckc commented on component/admin/models/wrappers.php
> +		}
@hoang-tran-redweb please check query with old model wapper in method _buildQuery

2020-07-20 02:38 UTC, hungnguyenckc commented on component/admin/updates/3.0.3.php
> +	        JPATH_ADMINISTRATOR . '/components/com_redshop/models/wrapper.php',
@hoang-tran-redweb No remove model/wrapper

2020-07-20 02:38 UTC, hungnguyenckc commented on component/admin/updates/3.0.3.php
> +	        JPATH_ADMINISTRATOR . '/components/com_redshop/views/wrapper/tmpl/index.html',
No remove view wrapper

2020-07-20 02:38 UTC, hungnguyenckc commented on component/admin/updates/3.0.3.php
> +            JPATH_ADMINISTRATOR . '/components/com_redshop/views/newsletter_detail/view.html.php'
@hoang-tran-redweb duplicate

2020-07-20 02:38 UTC, hungnguyenckc commented on component/admin/views/wrapper/view.html.php
> + * @since       2.0.0.6
@hoang-tran-redweb __DEPLOY_VERSION__

2020-07-27 02:50 UTC, hungnguyenckc requested changes

2020-07-27 02:50 UTC, hungnguyenckc commented on component/admin/models/wrapper.php
> + * @since       2.1.3
__DEPLOY_VERSION__

2020-07-27 02:50 UTC, hungnguyenckc commented on component/admin/models/wrappers.php
> +		);
two variables not used

2020-07-27 02:53 UTC, hungnguyenckc requested changes

2020-07-27 02:53 UTC, hungnguyenckc commented on component/admin/models/wrappers.php
> +
$orderCol, $orderDirn Not declared

2020-07-27 02:55 UTC, hungnguyenckc commented
@hoang-tran-redweb please see my comment and change request thank

2020-07-27 08:17 UTC, hoang-tran-redweb commented on component/admin/views/wrapper/view.html.php
> + * @since       2.0.0.6
@hungnguyenckc i fixed

2020-07-27 08:19 UTC, hoang-tran-redweb commented on component/admin/models/wrappers.php
> +
@hungnguyenckc I fixed

2020-07-27 08:19 UTC, hoang-tran-redweb commented on component/admin/models/wrappers.php
> +		);
@hungnguyenckc I fixed.

2020-07-27 08:19 UTC, hoang-tran-redweb commented on component/admin/models/wrapper.php
> + * @since       2.1.3
I fixed

2020-07-30 08:53 UTC, hungnguyenckc submitted a review, later dismissed

2020-08-04 02:24 UTC, NguyenTrang091296 commented
Please help me fix conflict cc @hoang-tran-redweb

2020-08-06 03:05 UTC, anhredweb submitted a review, later dismissed

2020-08-06 06:53 UTC, anhredweb approved these changes

2020-08-06 06:54 UTC, merged