REDSHOP-4091: REFACTOR: Newsletter Subscrible
redCOMPONENT-COM/redSHOP pull request #5459
Opened 2020-08-07 07:29 UTC by hoang-tran-redweb

2020-08-07 08:08 UTC, anhredweb requested changes
@hoang-tran-redweb : please help to change header to 2020. There still @since not __DEPLOY_VERSION__. Table name not same with class name, can we change it?

2020-08-07 08:42 UTC, hoang-tran-redweb commented
> @hoang-tran-redweb : please help to change header to 2020. There still @SInCE not **DEPLOY_VERSION**. Table name not same with class name, can we change it?

2020-08-07 08:43 UTC, hoang-tran-redweb commented
@anhredweb I changed. please review again.

2020-08-12 02:55 UTC, hungnguyenckc submitted a review, later dismissed

2020-08-18 03:20 UTC, anhredweb approved these changes

2020-08-18 03:20 UTC, merged